### ISSUE TITLE
WebApplicationException not caught by JAX-RS

### ISSUE THREAD

**Issue by amihaiemil** [sttc/stateful#17]
Currently anonymous calls to the counter API are not possible and an exception is thrown by the ``user()`` method: ``throw FlashInset.forward(...)``

http://www.stateful.co/c/3345/set?value=test

Cause: 

JAX-RS does not catch ``WebApplicationExceptions`` if the function is not an http method.

In this case, ``CounterRs`` uses the method ``public void setCounter(final String name)`` as intermediary to check the user identity and get his counters. This method is not currently http, it simply acts as a "proxy" to the other methods, by taking the ``@PathParam``. 

Solution: get rid of the method (or turn it into a GET for counter, but in this case it won't act as a proxy for the others anymore) and make the other methods digest the @PathParam and get their own counter to use (there are also a couple of different ways to do this).

**Comment by amihaiemil** [comment]
@yegor256 can you check this pls? Thanks

**Comment by amihaiemil** [comment]
@karato can u do something about this ticket? Thanks

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 Don't forget about this pls

**Comment by karato** [comment]
@yegor256 please dispatch this issue

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@amihaiemil this sounds like a valid bug, but not the way you explained it. we just need to check for counter existence beforehand and throw a proper exception (that's bug no.1) and we have to add an exception dispatcher to the entire application to make them look nicer (bug no.2). but both bugs are not valid in this project, since we have to migrate it first to Takes. after the migration both bugs will disappear.
